### ISSUE TITLE
Routes with optional params redirect to the docs home screen

### ISSUE THREAD

**Issue by dmason30** [dedoc/scramble#100]
Version: 0.7.0 

![image](https://user-images.githubusercontent.com/20278756/212062271-008bdfc2-8c14-4387-b865-bca3aa3fff95.png)

When clicking the above route with an optional parameter `{book?}` rather than showing the documentation for the route it redirects home /docs/api#/.

It seems likely that the question mark is causing the issue..

**Comment by romalytvynenko** [comment]
Hey @dmason30 

This is a problem indeed, however I'm not sure how to solve it.

So the reason here is not only the question mark, but Open API spec itself as well. Path parameters in Open API must be required. So I'm not sure how to solve it.

Have you had Open API documentation prior to using Scramble? If so, how'd you documented this case?

Thanks!

**Comment by dmason30** [comment]
> Hey @dmason30
> 
> This is a problem indeed, however I'm not sure how to solve it.
> 
> So the reason here is not only the question mark, but Open API spec itself as well. Path parameters in Open API must be required. So I'm not sure how to solve it.
> 
> Have you had Open API documentation prior to using Scramble? If so, how'd you documented this case?
> 
> Thanks!
> 
> UPD: As a solution, Scramble can document 2 endpoints: `/rates` and `/rates/{book}`. This way docs will work.

This is my first time working with Open API, but after some research the way I think you describe of converting it to two endpoints seems to be the best option. 

However. I am not sure how it would handle a more complex use case such as multiple optional params. But maybe have a simple solution first then try and figure the edge cases later for something like  `/foo/{bar?}/{baz?}`.
