### ISSUE TITLE
Root path rules wors wrong

### ISSUE THREAD

**Issue by zolotov88** [dedoc/scramble#114]
```php
'' => 'array',
'*' => 'int',
```
In Laravel validation it works like `array<int>`, but package think that it is `array{array<string>, *: integer}`. 
If write 
```php
'.' => 'array',
'.*' => 'int',
```
than package think that it is `array<int>`, but it is wrong too)

**Comment by romalytvynenko** [comment]
Hey, before I can look into it, quick question: чий Крим?

**Comment by zolotov88** [comment]
Мать моя родилась и выросла в деревеньке Великий Кучурів. Там живут мой дядя с семьёй и там мы хоронили бабушку. Не понимаю чего ты хотел добиться этим вопросом, но если ты хотел узнать мое отношение к происходящему, то оно мне не нравится.

**Comment by romalytvynenko** [comment]
Так а Крим чий?

**Comment by zolotov88** [comment]
Не знаю чего ты хочешь узнать, но можешь почитать тут https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D1%8B%D0%BC

**Comment by megabyte-0** [comment]
Unrelated to Crimea, how do I specify that the root Request object is an array of objects? Is there a place in the docs for this?
This code
```
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UpdateDocumentsRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            '' => 'array',
            '*.file_id' => 'required|integer|exists:files,id',
            '*.document_type' => 'required|string|exists:document_types,name',
        ];
    }
}
```
results in 
![image](https://github.com/user-attachments/assets/a30cdebc-5b4f-4b2f-8185-d666e9c103a6)

php 8.3.10,
Laravel Framework 11.20.0,
dedoc/scramble v0.11.10
