### ISSUE TITLE
Route param type is not changed by PhpDoc

### ISSUE THREAD

**Issue by Tryfciu** [dedoc/scramble#121]
Version: 0.7.2
Goal: change route param from integer to string

 route: `Route::put('/api/professions/{profession}', UpdateProfessionController::class)->middleware(['role:MANAGER']);`
 
 controller:
 ```
 /**
 * @tags Profession
 */
class UpdateProfessionController extends Controller
{
    /**
     * Update Profession
     * 
     * @param string $profession Profession ID which is of type UUID
     */
    public function __invoke(ProfessionStoreRequest $request, Profession $profession)
    {
        $profession->update($request->only('name'));

        return response()->json(null);
    }
}
 ```
 
 model:
 ```
 class Profession extends Model
{
    use HasUuids, HasFactory;

    protected $fillable = [
        'id',
        'name',
        'status',
    ];

    protected $casts = [
        'status' => ProfessionStatus::class,
    ];
}
 ```
 
![image](https://user-images.githubusercontent.com/28263270/230394262-70aadba8-33ba-4cf6-8a90-b682fb1908d5.png)

So as you can see despite having PhpDoc in controller, param is always marked as `integer` in dashboard and json documentation. I can still send string in this field, but in my particular case I use another tool to generate typescript classes from documentation so I finish with this field marked as number in typescript. It is also worth noticing that description of this field which is in the same line in controller PhpDoc is correct.

**Comment by romalytvynenko** [comment]
@Tryfciu thanks for reporting!


The fix was pushed in https://github.com/dedoc/scramble/pull/122 and will be released in the next version
