### ISSUE TITLE
Example string has no quotation marks

### ISSUE THREAD

**Issue by Tryfciu** [dedoc/scramble#145]
Version: 0.7.2
Goal: Have ability to explicitly type example value

 request:
 ```
class StoreUserRequest extends FormRequest
{
    public function rules(): array
    {
        return [
            // @example decade00-0000-4000-a000-000000000000
            'id' => 'uuid|required',
            // @example 700100200
            'phone_number' => 'nullable|string|digits:9',
        ];
    }
}
 ```
 
![image](https://github.com/dedoc/scramble/assets/28263270/755ef4cb-fc87-46d8-b577-066326393f68)

So as you can see despite having phone_number property marked as `string` in request, value in right section of dashboard has no quotation marks so request does not pass validation. Documentation in left part of dashboard is correct `phone_number string or null` but value in example request is not sent as string as long as it has no quotation marks. I can manually add quotation marks to value in request but doing it every time is frustrating. I tried everything that came to my mind to cast it inside my request class but did not manage to do that. Is there any solution in current version?

**Comment by romalytvynenko** [comment]
@Tryfciu thanks for report. This was done intentionally, as the simplest way to parse examples. So essentially they are parsed as a JSON. So simply putting a number without quotation marks will be a number.

There is no way to solve this in current version and I'm really hesitant to change this behavior.

Let me know what you think

**Comment by Tryfciu** [comment]
@romalytvynenko thank you for fast response. As far as I understand if examples are parsed as a JSON (json_decode) then example in this cofiguration (with quotation marks) should result in string value.
`// @example "700100200"` OR `// @example "\"700100200\""` should result in "700100200" but now result in 700100200.

I looked into `RuleToParameter.php` file and played a bit with lines 78-100 and it turned out, that `// @example "\"700100200\""` is actually resolved to "700100200" string by json_decode (line 83)  but somewhere later on this string is wrapped with another quotation marks pair so it ends up being: 
![image](https://github.com/dedoc/scramble/assets/28263270/51e472ba-afeb-40c8-9b04-150c842e8aa6) again.

I managed achieve what I want by adding this condition (RulesToParameter.php): 
![image](https://github.com/dedoc/scramble/assets/28263270/4a825523-a998-4a45-9a0b-0282930cf46c)

and then make example this way:

``` 
// @example 700100200
'user_private_phone_number' => 'nullable|string|digits:9',
```

By applying this condition you need to specifically state that property in request is `int`:
```
// @example 700100200
'user_private_phone_number' => 'nullable|int|digits:9',
```
 to make example number rather than string. On the other hand my solution is probably not the best option there and maybe there is not other option in current version. BUT I'm letting you know that i managed to do so maybe it will make clear what I want to achieve or inspire you to do it in some other way. 

Let me know if my explanation and expected result is clear.

**Comment by Neorej** [comment]
Any chance the `instanceof`-check mentioned above can be implemented? This fixes a problem I have:
The example tag currently does not allow numeric strings with leading zeroes to be displayed properly: `0123` turns into `123`

Another solution would be to maybe add string keys to the extensions array here, so we can overwrite them (the `array_values` call would need to be removed too), but maybe this is a bigger hassle.
https://github.com/dedoc/scramble/blob/379093f786cfab90110cb4e77dcd92facedb97e8/src/ScrambleServiceProvider.php#L101-L111

**Comment by joligoms** [comment]
This sounds like a big deal and should really be implemented to be very honest. Parsing a string that is numeric, even though the validation being set is a string, doesn't sound very coherent for the API documentation itself in my opinion.
But are there any drawbacks to not include what @Tryfciu made?

**Comment by romalytvynenko** [comment]
@joligoms please feel free to open a PR.

**Comment by joligoms** [comment]
Hi @romalytvynenko, sorry for the late response. I made the PR with a brief summary of the fix. Let me know what you think about it! Cheers ;)

**Comment by qLutCh55** [comment]
I am experiencing the same issue with Scramble Pro and Laravel Data.

![image](https://github.com/user-attachments/assets/a21a36f2-43d9-459f-a84a-9b750d6fc206)
![image](https://github.com/user-attachments/assets/e5d32837-e2de-4b47-a8a1-233eed82e8d2)

Not sure if I need to adjust some annotation?

**Comment by qLutCh55** [comment]
Just removed the transformer, issue still persists.

**Comment by qLutCh55** [comment]
Amazing, working now - thank you very much
