### ISSUE TITLE
ModelInfo->getCastsWithDates() - array_flip error

### ISSUE THREAD

**Issue by deffjay** [dedoc/scramble#164]
I am getting the following error when generating API documentation for my Laravel 10 project. 

"array_flip(): Can only flip string and integer values, entry skipped {"exception":"[object] (ErrorException(code: 0): array_flip()"

The array that $model->getDates() returns when this blows up, looks like this:
```
local.DEBUG: Array
(
    [0] => created_at
    [1] =>
)
```

It appears that $model->getDates() returns an array of two entries; however, one is null. I'm not sure why this is happening. However, it's easy to modify getCastType() to not blow up and return a null when calling getCastsWithDates(); it appears to work fine.

ModelInfo.php: Line 323

**Comment by romalytvynenko** [comment]
@deffjay fixed in 0.8.1

https://github.com/dedoc/scramble/releases/tag/v0.8.1

**Comment by deffjay** [comment]
@romalytvynenko - excellent, thank you. I just verified on 0.8.1.
