### ISSUE TITLE
Call to a member function isInstanceOf() on null – vendor/dedoc/scramble/src/Support/InferExtensions/JsonResourceTypeInfer.php on line 78

### ISSUE THREAD

**Issue by deffjay** [dedoc/scramble#166]
Error when analyzing route 'GET v1/search/omni' (App\Http\Controllers\Search\OmniSearchController@search): Call to a member function isInstanceOf() on null – /var/www/html/vendor/dedoc/scramble/src/Support/InferExtensions/JsonResourceTypeInfer.php on line 78

Looks like a simple null member fix.

`[2023-08-06 05:39:10] local.ERROR: Error: Call to a member function isInstanceOf() on null in /var/www/html/vendor/dedoc/scramble/src/Support/InferExtensions/JsonResourceTypeInfer.php:78
Stack trace:
#0 /var/www/html/vendor/dedoc/scramble/src/Infer/Handler/ExpressionTypeInferringExtensions.php(29): Dedoc\Scramble\Support\InferExtensions\JsonResourceTypeInfer->getType()
#1 [internal function]: Dedoc\Scramble\Infer\Handler\ExpressionTypeInferringExtensions->Dedoc\Scramble\Infer\Handler\{closure}()
#2 /var/www/html/vendor/dedoc/scramble/src/Infer/Handler/ExpressionTypeInferringExtensions.php(35): array_reduce()
#3 /var/www/html/vendor/dedoc/scramble/src/Infer/TypeInferer.php(93): Dedoc\Scramble\Infer\Handler\ExpressionTypeInferringExtensions->leave()
#4 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(153): Dedoc\Scramble\Infer\TypeInferer->leaveNode()
#5 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#6 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#7 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode()
#8 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()
#9 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray()
#10 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode()
#11 /var/www/html/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode()`

**Comment by romalytvynenko** [comment]
@deffjay thanks for the report. Can you share coded examples of your controller and json resource?

**Comment by deffjay** [comment]
This Controller has a lot going on with it. This may help us reduce the surface area of the issue.

Here is the value of $node from within getType() method @ JsonResourceTypeInfer.php:

local.DEBUG: PhpParser\Node\Expr\PropertyFetch Object
(
    [attributes:protected] => Array
        (
            [startLine] => 90
            [endLine] => 90
        )
    [var] => PhpParser\Node\Expr\PropertyFetch Object
        (
            [attributes:protected] => Array
                (
                    [startLine] => 90
                    [endLine] => 90
                )
            [var] => PhpParser\Node\Expr\Variable Object
                (
                    [attributes:protected] => Array
                        (
                            [startLine] => 90
                            [endLine] => 90
                        )
                    [name] => roster
                )
            [name] => PhpParser\Node\Identifier Object
                (
                    [attributes:protected] => Array
                        (
                            [startLine] => 90
                            [endLine] => 90
                        )
                    [name] => pivot
                )
        )
    [name] => PhpParser\Node\Scalar\String_ Object
        (
            [attributes:protected] => Array
                (
                    [startLine] => 90
                    [endLine] => 90
                    [kind] => 1
                    [rawValue] => 'team_player_roster_to_player.created_at'
                )
            [value] => team_player_roster_to_player.created_at
        )
)

What other information do you need?

**Comment by romalytvynenko** [comment]
@deffjay any chance you can leave only the code (controller's) that causes the issue and share that?

I would really appreciate that, as it is really hard to reproduce the issue just from var dumps.

**Comment by romalytvynenko** [comment]
@deffjay fixed in 0.8.2

https://github.com/dedoc/scramble/releases/tag/v0.8.2

**Comment by deffjay** [comment]
@romalytvynenko - Thanks for this! 

Sorry - I didn't check this thread until just now.

**Comment by deffjay** [comment]
Confirming this fixes the original issue.
