### ISSUE TITLE
Unable to parse variable in JsonResponse string for Example value

### ISSUE THREAD

**Issue by kichetof** [dedoc/scramble#178]
Hi,

Thanks a lot for you great package, really impressed how it can grab everything!!

I noticed a bug when your response contains a variable.
You can try something like that in your controller:

```php
class ResourceController extends Controller
{
    public function store(ResourceStoreRequest $request): JsonResponse
    {
        return response()->json(['message' => "Resource created"], 201);
    }
}
```
Will return message _string_ with example `Resource created`

<img width="339" alt="Capture d’écran 2023-08-17 à 15 53 35" src="https://github.com/dedoc/scramble/assets/12150996/a3585ed0-65cf-48af-9234-8928c7b9a792">

---

```php
class ResourceController extends Controller
{
    public function store(ResourceStoreRequest $request): JsonResponse
    {
        $x = 'test';

        return response()->json(['message' => "Resource $x created"], 201);
    }
}
```
Will return message _string_ without example

<img width="311" alt="Capture d’écran 2023-08-17 à 15 53 55" src="https://github.com/dedoc/scramble/assets/12150996/97d65cfb-1e26-4dea-b480-5f5d61ae9268">

---

Maybe you've another solution to display example for this such of situation? _(already tried @var and @example)_

Thanks a lot for your help!
Christophe

**Comment by romalytvynenko** [comment]
@kichetof hey

This is an intended behavior regarding "example" part. In your comment example is really simple. But in reality that var can be whatever.

I recommend you to simply use a response annotation using `@body` if you want to have an example: 

<img width="636" alt="image" src="https://github.com/dedoc/scramble/assets/6153876/5207a08d-00b6-474b-be0a-6609a72b243d">
<img width="562" alt="image" src="https://github.com/dedoc/scramble/assets/6153876/73e24521-1a4e-486a-9910-ed71c8b4b9c6">

**Comment by kichetof** [comment]
@romalytvynenko thanks a lot it works perfectly for `200` response!

I tried with another controller who return both:
```php
class ResourceController extends Controller
{
    public function store(ResourceStoreRequest $request): JsonResponse
    {
        $x = 'test';

        if(Ressource::alreadyExists()) {
            /** @body array{"message": "Resource test already exists"} */
            return response()->json(['message' => "Resource $x already exists"], 422);
        }

        /** @body array{"message": "Resource test created"} */
        return response()->json(['message' => "Resource $x created"], 201);
    }
}
```

Response example works well for 201, but not for 422:
<img width="413" alt="Capture d’écran 2023-08-17 à 16 34 06" src="https://github.com/dedoc/scramble/assets/12150996/6ca11db0-3c45-46ee-94dd-d31deb0a1fb7">

Both message are located inside 200 response

Thanks a lot for your help!

**Comment by romalytvynenko** [comment]
@kichetof alongside `@body` you can use `@code` annotation to specify status

https://scramble.dedoc.co/usage/response#response-description
