### ISSUE TITLE
Array validation in documentation (With)

### ISSUE THREAD

**Issue by slnw** [dedoc/scramble#186]
Hi, I'm trying to add the with.* validation like so
```php
    public function index(Request $request)
    {
        $request->validate([
            'with.*' => 'sometimes|in:offers,sends,logs',
        ]);

        //...
    }
 ```

Unfortunately when making the request **through the docs** I receive the following error:
![Screenshot 2023-08-20 at 22 04 41](https://github.com/dedoc/scramble/assets/26124406/f18b2c42-221a-4413-8268-c6b84b06c9f7)

"Cannot use param value "['offers']". JSON array expected."

(I tried other variations of validation and text in the doc, the request works from curl.

thanks.

**Comment by romalytvynenko** [comment]
@slnw have you tried using '["offers"]' in UI (double quotes, not singular)?
