### ISSUE TITLE
`getRouteKeyName` on model ignored

### ISSUE THREAD

**Issue by orchidlive** [dedoc/scramble#191]
I have route model binding set up with a column called `uuid` that is not the primary key of the table. Laravel allows me to use this column as the route parameter by overriding the `getRouteKeyName` function, for example, in the model

```
class MyModel extends Model
{
    /**
     * Get the route key for the model.
     */
    public function getRouteKeyName(): string
    {
        return 'uuid';
    }
}
```

I think Scamble is ignoring this as it's still listed as an integer in the generated docs.

As a workaround, I followed the steps to override the parameter type following the guidance in the Requersts -> Route params section of the documentation. for example,

```
class EmployeeController
{
    /**
     * @param string $employee uuid of employee.
     */
    public function update(Request $request, Employee $employee)
    {
        // ...
    }
}
```
However, it still shows in the documentation as an integer.

![s](https://github.com/dedoc/scramble/assets/62140676/8d9c3177-a733-4516-8d25-02455c146249)

**Comment by kjbenk** [comment]
I have been able to confirm this issue as well. I am using the Route method `scoped` to scope model binding to a certain column. Maybe there is a way to hook into custom model binding logic to ensure this is used when generating docs.
