### ISSUE TITLE
hi i quite like your library but when i combine with this package https://restify.binarcode.com/quickstart/ it is having problem its not able to generate doc for api do you have any solution for the problem is this not?

### ISSUE THREAD

**Issue by trihai306** [dedoc/scramble#193]
hi i quite like your library but when i combine with this package https://restify.binarcode.com/quickstart/ it is having problem its not able to generate doc for api do you have any solution for the problem is this not?

**Comment by Wulfheart** [comment]
Could you please provide an exact error description?

**Comment by trihai306** [comment]
it's a package that creates an api but your package is not compatible with it and it doesn't show the documentation for the api i created even though it already exists

**Comment by Wulfheart** [comment]
That's 1. not an exact error description and 2. not reproducible by any means.

**Comment by romalytvynenko** [comment]
@trihai306 closing the issue as this is about supporting third-party library.

I don't plan to add that to Scramble, or to develop it.

Feel free to use Scramble's extensions system to create support for that library. 

Thanks.
