### ISSUE TITLE
docs/api not found

### ISSUE THREAD

**Issue by lionalex** [dedoc/scramble#201]
I installed on my laravel v10.20 with composer, but when I go on docs/api or docs/api.json, the system give me error 404 not found.
Why? I try it on my localhost server.

**Comment by romalytvynenko** [comment]
@lionalex I don't know why. 

Have you checked the output of `routes:list` command?

**Comment by Wulfheart** [comment]
Furthermore could you please evaluate whether the package has been properly installed?

**Comment by lionalex** [comment]
@romalytvynenko thanks for your suggest: in effect there was another root that give conflict.
Resolved.

Thank you all
