### ISSUE TITLE
Doc generation fails when having multiple return possibilities

### ISSUE THREAD

**Issue by jogehl** [dedoc/scramble#227]
The doc generation fails building the description if there are multiple return possibilities.

**Comment by romalytvynenko** [comment]
@jogehl please elaborate: share some examples, share expected and actual outcomes.

I have no idea what to fix here.

**Comment by romalytvynenko** [comment]
@jogehl you should move the dot to the method. Leaving just random comments won't be taken into docs.

```php
    /**
     * Test endpoint.
     *
     * Example descrtiption.
     */
    public function test()
    {
        if (3>2)
            return response()->json('test', 404);
        return response()->json('test', 201);
    }
```

Please check the docs: https://scramble.dedoc.co/usage/response#response-description
