### ISSUE TITLE
OpenAPI info block

### ISSUE THREAD

**Issue by DaGLiMiOuX** [dedoc/scramble#23]
Hi there,

First of all let me thank you for this amazing package. Is so easy to use and very useful. We recently had to implement OpenAPI for a project and we were using OpenAPI package from Laravel-OpenAPI and was really painful to create doc blocks, create OpenAPI classes for each OpenAPI section, etc.

Btw, I didn't find any information about how to configure info block in dedoc/scramble package documentation. I don't know if that is possible via config file or something like that, but would be awesome. I ask it, because I would like to change the `version` in info block of the OpenAPI JSON string.

Searching in the sources, I've found this line of code in `Generator.php`:
```php
// Generator.php
$openApi = OpenApi::make('3.1.0')
            ->setComponents($this->transformer->getComponents())
            ->setInfo(InfoObject::make(config('app.name'))->setVersion('0.0.1'));
```
And would be nice to have something like this:
```php
// Generator.php
$openApi = OpenApi::make('3.1.0')
            ->setComponents($this->transformer->getComponents())
            ->setInfo(InfoObject::make(config('app.name'))->setVersion(config('scramble.info.version')));
```
```php
// config/scramble.php
return [
    // ...
    'info' => [
        'version': env('OPENAPI_INFO_VERSION', '0.0.1'),
    ]
];
```
This was just an example, but I hope you get the idea.

Thanks for your time on reading this.

Best regards,
D.

**Comment by romalytvynenko** [comment]
@DaGLiMiOuX 

Yeah, `config('scramble.version')` will be really hard to implement. Taking into account that docs are generated from the scratch and rendered by the package itself, I don't see much added value in supporting old versions. 

`info` block idea is good BTW! Thanks!
