### ISSUE TITLE
There is a problem with calling Validation via a variable

### ISSUE THREAD

**Issue by salawatbro** [dedoc/scramble#235]
### Discussed in https://github.com/dedoc/scramble/discussions/233

<div type='discussions-op-text'>

<sup>Originally posted by **SalawatJoldasbaev** September 25, 2023</sup>
That's how I wanted to use it:
$request->validate($data->rules());

<img width="773" alt="image" src="https://github.com/dedoc/scramble/assets/70514229/e0f9ef6d-98d7-4d2e-b261-79e2db63c59e">

But how can you fix such an error?
⚠️Cannot generate request documentation: Undefined variable $data

<img width="688" alt="image" src="https://github.com/dedoc/scramble/assets/70514229/f5128121-fd22-4942-afc9-fb7ee30256d6">
</div>

**Comment by abdielbytes** [comment]
You'd need to add a fallback for it to work.

**Comment by salawatbro** [comment]
> You'd need to add a fallback for it to work.

thank you
