### ISSUE TITLE
Timestamp columns are incorrectly recognized as objects, instead of a string with the date-time format

### ISSUE THREAD

**Issue by Wirewraith** [dedoc/scramble#239]
This only seems to occur if returning a Resource object from a route, whereas returning a model directly correctly infers the type.

**Comment by romalytvynenko** [comment]
@Wirewraith can you please share your controller's method and resource's code?

**Comment by Wirewraith** [comment]
RedirectResource.php

```php
<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class RedirectResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'from' => $this->from,
            'to' => $this->to,
            'visits' => $this->visits,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
```

A controller method returning it:
```php
    /**
     * Add
     *
     * Add a new redirect
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'from' => 'required|string',
            'to' => 'required|url',
        ]);

        $redirect = new Redirect();
        $redirect->from = $data['from'];
        $redirect->to = $data['to'];
        $redirect->save();

        return new RedirectResource($redirect);
    }
```

The result in Stoplight:
![image](https://github.com/dedoc/scramble/assets/15199527/a2cf2014-63f2-452a-a990-26c820516207)

**Comment by adjustmentlayer** [comment]
You see `object` type because  the `updated_at` and `created_at` property has a `Carbon` instance inside, not a string, therefore Scramble thinks, that you are returning an object.
Personally I resolved this problem like this
```php
'created_at' => (string)$this->created_at,
'updated_at' => (string)$this->updated_at
```
But I think that Scramble should be smart enough to see a `Carbon` instance as a `string`, or even more so, to see every object that has `__toString` method as a string

**Comment by juliansteenbakker** [comment]
Hi all, i am using version 0.9.0, but i still have this issue where the created_at is casted to an object instead of a string.

**Comment by romalytvynenko** [comment]
Hey @juliansteenbakker 

Please share your code example where you use created at. Also model's class would be great
