### ISSUE TITLE
Stoplight doesn't recognise file type parameters as file inputs

### ISSUE THREAD

**Issue by Wirewraith** [dedoc/scramble#240]
See the Stoplight docs here: https://docs.stoplight.io/docs/platform/c2f20944173d7-work-with-media-types

Currently the "Try it" section only shows any file input as a string.

**Comment by romalytvynenko** [comment]
This is nice, but seems like it is not working for Elements UI. Scramble already correctly set request media type, but there is no file input. Feel free to submit a PR if this is a mistake.
