### ISSUE TITLE
Ressource Array-KeyConstants are not validated

### ISSUE THREAD

**Issue by subIT1** [dedoc/scramble#256]
When having a Ressource-Structure where the toArray-Function has a definition - the analysis does not wokt when constants are used.

So what woks is the following Structure 
<img src="https://github.com/dedoc/scramble/assets/15226996/a0a1baa3-5b2e-4978-8521-48f9cc697905" width="600">
which resolves in 
<img src="https://github.com/dedoc/scramble/assets/15226996/b118263d-630f-4bb2-b14e-a9969e7908a7" width="300">

**But** when changing the array-keys into constants like this
<img src="https://github.com/dedoc/scramble/assets/15226996/74f352cb-c015-4e86-9b3e-e6c2f2cb70b2" width="600">
the resove is this
<img src="https://github.com/dedoc/scramble/assets/15226996/06b6fc49-07d2-4c83-a418-d4cc427efa43" width="300">

So the validation/identification of the constants does not work.

Using these versions:
"php": "^8.2",
"laravel/framework": "^v10.24.0",
"dedoc/scramble": "^0.8.4",
"doctrine/dbal": "^3.7",

**Comment by romalytvynenko** [comment]
Should be fixed after `226-docs-generation-fails-for-requests-that-utilise-custom-values` is merged. Closing for now
