### ISSUE TITLE
Have an error Target [\Illuminate\Database\Eloquent\Model] is not instantiable.

### ISSUE THREAD

**Issue by SquanchInHere** [dedoc/scramble#257]
Target [\Illuminate\Database\Eloquent\Model] is not instantiable.

**Comment by romalytvynenko** [comment]
@SquanchInHere Can you share more info? Where exactly this exception happens?

**Comment by SquanchInHere** [comment]
@romalytvynenko Sorry about that it was my fault.

**Comment by SquanchInHere** [comment]
@romalytvynenko  Thanks anyway for the quick response !
