### ISSUE TITLE
Add @example for response types

### ISSUE THREAD

**Issue by slnw** [dedoc/scramble#264]
for example:
```php
* @example {
 *   "fields": [
 *     {
 *       "field": "foo_count",
 *       "label": "Foo Count",
 *       "type": "integer",
 *       "operators": ["equal", "not_equal", "less", "less_or_equal", "greater", "greater_or_equal"]
 *     },
 * ]}
 ```

**Comment by romalytvynenko** [comment]
@slnw can you please share more full example? Like should this be in controller or resource,  etc

**Comment by slnw** [comment]
I found a workaround with implementing extension, but i guess it should be in controller or resource. The idea is to provide in the example section of the API real values. maybe better to connect it to the factory of model if HasFactory?

**Comment by hamge96** [comment]
> I found a workaround with implementing extension, but i guess it should be in controller or resource. The idea is to provide in the example section of the API real values. maybe better to connect it to the factory of model if HasFactory?

Hi @slnw, would you mind sharing how you achieved adding an example response value through implementing extension?

**Comment by michaelhrivnak** [comment]
This would be very handy, currently having to do something like this in my API Resource:

```php
 public function toArray(Request $request): array
    {
        return [
            'name' => $this->name,
            'description' => $this->description,
            /**
             * @var string $bg_color hex color code — format: #RRGGBB or #RRGGBBAA
             */
            'bg_color' => $this->bg_color,
        ];
    }
    ```

would be great to be able to do:

```php
public function toArray(Request $request): array
    {
        return [
            'name' => $this->name,
            'description' => $this->description,
            /**
             * @var string $bg_color hex color code — format: #RRGGBB or #RRGGBBAA
             * @example #00FF00
             */
            'bg_color' => $this->bg_color,
        ];
    }
```

**Comment by hamge96** [comment]
I found a temporary solution by implementing the ability to convert `@example` in the description for each field in the response into an example value.

1. Copy the vendor file `vendor/dedoc/scramble/src/Support/Generator/Types/Type.php` into any folder within your project. For example, you can place it at `app/Libraries/Scramble/Support/Generator/Types/Type.php`.

2. Retain all the source code in the file, including the namespace and class aliasing. Only override the `setDescription` method as follows:

```php
public function setDescription(string $description): Type
{
    $this->description = $description;

    if (Str::of($description)->contains('@example ')) {
        [$message, $example] = with($description, function ($description) {
            $parts = explode('@example', $description);

            $example = with(Str::of($parts[1])->trim(), function ($example) {
                if ($example == 'true') {
                    return true;
                }

                if ($example == 'false') {
                    return false;
                }

                if ($this->type === 'array') {
                    return json_decode($example);
                }

                if ($this->type === 'integer') {
                    return (int) $example->value;
                }

                return $example;
            });

            return [Str::of($parts[0])->trim(), $example];
        });

        $this->description = $message;
        $this->example = $example;
    }

    return $this;
}
```

3. Edit your project's root `composer.json`, and modify `"exclude-from-classmap"` and `"psr-4"` under `"autoload"` to look similar to the following:

```
"autoload": {
  "exclude-from-classmap": [
    "vendor\\dedoc\\scramble\\src\\Support\\Generator\\Types\\Type.php"
  ],
  "psr-4": {
    "Dedoc\\Scramble\\": "app/Libraries/Scramble"
  }
},
```

4. Run the following command to apply the overrides:

```
composer dump-autoload
```

This process allows you to manually include example response values by using the @example tag in the description for each field in the response:

```php
<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class AuthenticationTokenResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return [
            // @var string Token for authentication. @example 34|qqq9U3HDAVPa7ISFuOW0fWYFLCFqvDhsoqE6Ak8b38c31368
            'token' => $this->createToken($request->userAgent())->plainTextToken,
        ];
    }
}
```
will show like:
![dedoc-scramble-example-response](https://github.com/dedoc/scramble/assets/100076627/e807523b-078f-4a86-9f14-c4184d17821b)

**Comment by michaelhrivnak** [comment]
> I found a temporary solution by implementing the ability to convert `@example` in the description for each field in the response into an example value.
>
> ... 
>

Thanks for the work around @hamge96 Related to this and I should make another issue is that the parser strips out '//' from the content of descriptions so examples can't contain full urls. 

I added this to your solution:

```php
if(Str::of($example)->contains(['http:','https:']))
{
    $example = preg_replace('(https?:)','$0//',$example);
}
```

as a simple work around for now

looking forward to a real supported solution using full /** */ style

**Comment by nooxx** [comment]
Hello, thanks for adding this.

However it is not working for me. Here is my controller and resource:

Controller
```php
/**
     * ADA stakes
     * @response array{data: AdaStakesResource[]}
     */
    public function stakes(AdaStakesRequest $request)
    {
        //...
        return AdaStakesResource::collection($response->json()['data']);
    }
```

Resource:
```php
<?php

namespace App\Resources\ADA;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class AdaStakesResource extends JsonResource
{
    public function toArray(Request $request)
    {
        return [
            /**
             * @example my example
             *
             */
            'stake_address' => $this->resource['stake_address'],
        ];
    }
}
```

Result:
<img width="1406" alt="Screenshot 2024-03-24 at 00 06 42" src="https://github.com/dedoc/scramble/assets/6512445/9a009a93-83d7-40a0-8ed4-f173126a0c73">

**Comment by romalytvynenko** [comment]
@nooxx it is not yet released.
