### ISSUE TITLE
Attempt to read property "methods" on null

### ISSUE THREAD

**Issue by dmason30** [dedoc/scramble#307]
Laravel 10.x | Scramble 0.8.5 | PHP 8.3.x

Error occurs when requesting `docs/api.json` and breaks the loading of the whole docs site:

<img width="1377" alt="image" src="https://github.com/dedoc/scramble/assets/20278756/938ecd71-a1d7-4772-b280-ed1fb3c897be">

The `getClassDefinition` method has a return type of `?ClassDefinition` yet the `MethodAnalyzer::analyze` method does not accommodate for this.

I did some debugging and it seems to be unable to find the `ExchangeRateResourceCollection` ClassDefinition which is a standard Laravel class that extends `Illuminate\Http\Resources\Json\ResourceCollection`:
```php
/** @tags Rates */
class ExchangeRatesController extends Controller
{
    /**
     * Search Rates
     *
     * @param ?ExchangeRateBook $book Find the current rates for this rate book.
     */
    public function __invoke(ExchangeRatesRequest $request, ExchangeRateBook $book = null)
    {
        $book ??= app(SessionRateBook::class);

        /** @var ExchangeRateCollection $rates */
        $rates = ExchangeRate::book($book->id)
            ->base($book->base_currency_id)
            ->with(['baseCurrency', 'targetCurrency'])
            ->get()
            ->sortByTargetCurrencyRanking();

        abort_if($rates->isEmpty(), 404);

        return new ExchangeRateResourceCollection($rates);
    }
}
```

**Comment by romalytvynenko** [comment]
Hey @dmason30 

Can you share the implementation of `ExchangeRateResourceCollection`?

**Comment by dmason30** [comment]
@romalytvynenko Here it is, it is just used to add some meta data to the collection. i should say this was working fine in a previous version of this package and rendering the docs without issue. This route has not been changed in a couple years.

```php
class ExchangeRateResourceCollection extends ResourceCollection
{
    public function with($request)
    {
        $config = RateConfig::driver();

        return [
            'meta' => [
                'operators' => [
                    'calculation' => [
                        'charge' => $config->chargeOperator(),
                        'quantity' => $config->quantityOperator(),
                    ],
                    'comparison' => [
                        'gt' => $config->greaterThanOperator(),
                        'gte' => $config->greaterThanOrEqualToOperator(),
                        'lt' => $config->lessThanOperator(),
                        'lte' => $config->lessThanOrEqualToOperator(),
                        'percentage' => $config->percentage(),
                    ],
                ],
                'templates' => $config->translator()->templates()->toArray(),
            ],
        ];
    }
}
```

**Comment by romalytvynenko** [comment]
@dmason30 cannot reproduce. Any chance you can create a simple Laravel project repo with reproduction of this issue?

**Comment by rcerljenko** [comment]
I have the same problem mentioned here: https://github.com/dedoc/scramble/issues/352

**Comment by romalytvynenko** [comment]
@dmason30 can you please check if the issue persists on `v0.10.5`?

**Comment by rcerljenko** [comment]
I tried it and it's still happening... only under octane  :(

**Comment by romalytvynenko** [comment]
@rcerljenko yeah, on Octane it still persists. The question here is if it's still happening for @dmason30 as I'm not sure Dan's case is about Octane.

**Comment by dmason30** [comment]
Unfortunately I don't have access to that project anymore (I have changed jobs). There is a chance this was running on octane locally when I encountered the error as we definitely ran it on octane on prod.

**Comment by rcerljenko** [comment]
@romalytvynenko I can be your production tester if you want. I currently have a project tjat is active in dev and deployed to Linux Octane prod server

**Comment by romalytvynenko** [comment]
@rcerljenko Nice, thanks! If you can create a repro repo that I can simply install and get this issue – this also would be great 😊
