### ISSUE TITLE
php 8.2 and laravel 10. php-parser version 5 not compatible

### ISSUE THREAD

**Issue by karunkshrestha** [dedoc/scramble#309]
dedoc/scramble requires nikic/php-parser ^4.0, but laravel 10 has it locked to version 5. I was wondering if scramble is compatible with laravel 10.

**Comment by igorsgm** [comment]
I'm also with the same issue.

**Comment by SVV-team** [comment]
> Hey @karunkshrestha
> 
> I need more info. What do you mean Laravel 10 is locked to version 5? I don't see Laravel is dependent on `nikic/php-parser` at all.

Another packages depend on nikic/php-parser
And in lock files all of them waiting for 4 or 5 version ("nikic/php-parser": "^4.0|^5.0")
And only dedoc requrie version 4. But system already has v5)

**Comment by mammadataei** [comment]
```
- dedoc/scramble[v0.0.1, ..., v0.7.1] require illuminate/contracts ^8.0.0|^9.0.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
- dedoc/scramble[v0.7.2, ..., v0.8.6] require nikic/php-parser ^4.0 -> found nikic/php-parser[v4.0.0, ..., v4.18.0] but the package is fixed to v5.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
- Root composer.json requires dedoc/scramble * -> satisfiable by dedoc/scramble[v0.0.1, ..., v0.8.6].
```

**Comment by romalytvynenko** [comment]
@mammadataei @SVV-team please create reproduction repo with the project that will have the same issue. Otherwise I won't be able to help.

**Comment by romalytvynenko** [comment]
@mammadataei which PHP version do you use? Works for me on 8.1
