### ISSUE TITLE
How could we handle passport auth?

### ISSUE THREAD

**Issue by amm834** [dedoc/scramble#320]
I cannot find a documentation regarding to the laravel passport and how could we set Beare token in the request header?

**Comment by sydgren** [comment]
Did you look at the Security section of the docs?

https://scramble.dedoc.co/usage/security#oauth2

**Comment by amm834** [comment]
Yes I have looked into that doc, our approach is a bit different from that. We are using oauth for only personal access token. Not like above doc is documented. Thank you.

**Comment by romalytvynenko** [comment]
Closing for now, if still relevant please provide more info.
