### ISSUE TITLE
Add ability to specify data format manually

### ISSUE THREAD

**Issue by romalytvynenko** [dedoc/scramble#328]
Add an ability to specify data format in response:

```php
return [
    /**
     * @format date-time
     */
    'updated_at' => $this->updated_at->toDateTimeString(),
];
```

See: https://spec.openapis.org/oas/v3.1.0#data-types

Previous implementation: https://github.com/dedoc/scramble/pull/287

Concerns: 
- Is there a better API to do this? Maybe `string<date-time>` (but this type does not make sense for other static analysis tools). 
- Should it be available for both response and request fields?

**Comment by WildEgo** [comment]
Using something like ``` @var string<date-time>``` would feel more php-ish imo

**Comment by WildEgo** [comment]
> Using something like ` @var string<date-time>` would feel more php-ish imo

Actually piggy backing on this it would be nice to add `string<email>` and some others, basically set the type of the string inside the `<>`, what do you think @romalytvynenko
