### ISSUE TITLE
Add changelog generation and versioning

### ISSUE THREAD

**Issue by mammadataei** [dedoc/scramble#338]
I think it would be helpful if Scramble could generate a changelog for schema changes and determine the API version based on those changes.

Please check out this Node.js package: [openapi-diff](https://www.npmjs.com/package/openapi-diff).
It identifies changes to the schema and classifies them as breaking or non-breaking. This allows for generating an API changelog and automatically determines the API version bump.
It's also useful for detecting any unintentional breaking changes to the API.

I believe Scramble can compare changes if it stores the previous schema version.

**Comment by romalytvynenko** [comment]
Hey @mammadataei.

This feature was already planned for Scramble-based paid product (https://dedoc.co).
