### ISSUE TITLE
Error when running under Octane (Swoole)

### ISSUE THREAD

**Issue by rcerljenko** [dedoc/scramble#352]
Hi,

When running under octane this error happens and after I hit refresh 2 or 3 times it's gone. :/

![image](https://github.com/dedoc/scramble/assets/16762056/0746f840-73e3-4cac-a3fc-a5e33ec7592c)

![image](https://github.com/dedoc/scramble/assets/16762056/5160b48e-3d1f-4604-9f1d-e1e93dbfb5d7)

**Comment by romalytvynenko** [comment]
@rcerljenko should be fixed in [v0.10.7](https://github.com/dedoc/scramble/releases/tag/v0.10.7)

**Comment by rcerljenko** [comment]
many thanks!!!

**Comment by romalytvynenko** [comment]
@rcerljenko works fine on `v0.10.7`?

**Comment by rcerljenko** [comment]
Yes it does!  :)
