### ISSUE TITLE
❌ Code error : Path cannot be empty | Laravel

### ISSUE THREAD

**Issue by CalixteManaud** [dedoc/scramble#353]
Hi, I'm developing an API in laravel with docker. I've finished my project and now I'd like to implement Scrumble. Except when I consult the link: localhost:7040/docs/api, I get an error code that I don't understand.

Here's my error: 

Error when analyzing route 'GET api/validate' (App\Http\Controllers\AuthController@validateToken): Path cannot be empty - /var/www/vendor/dedoc/scramble/src/Infer/Reflector/MethodReflector.php on line 40

```php

    public function validateToken(Request $request): JsonResponse
    {
        $token = $request->bearerToken();
        try {
            $decoded = JWT::decode($token, new Key(base64_decode(env("PRIVATE_KEY")), 'HS512'));
            $now = new DateTimeImmutable();
            $expirationDate = (new DateTimeImmutable())->setTimestamp($decoded->exp);
            return response()->json([
                'token' => $token,
                'valid' => $now < $expirationDate,
                'expiration' => $expirationDate->format('Y-m-d H:i:s'),
            ]);
        } catch (\UnexpectedValueException $e) {
            Log::error('JWT error: ' . $e->getMessage());
            return response()->json(['error' => 'Invalid token'], 401); // Pour les erreurs de token JWT
        }  catch (\Exception $e) {
            Log::error('JWT error 2: ' . $e->getMessage());
            return response()->json(['error' => 'Invalid or expired token'], 401);
        }
    }
```
Here is my api.php file :

```php
Route::post('register', [AuthController::class, 'register'])->middleware('throttle:10,1');
Route::post('login', [AuthController::class, 'login']);
Route::get('/users', [AuthController::class, 'index']);
Route::middleware('jwt')->group(function () {
    Route::put("/account/{id}", [AuthController::class, 'update']);
    Route::post('/refresh-token', [AuthController::class, 'refreshToken'])->middleware('throttle:10,1');
    Route::get('/validate', [AuthController::class, 'validateToken']);
    Route::get("/account/{id}", [AuthController::class, 'view']);
});
```

**Comment by joeljohn135** [comment]
1. Ensure there's no mismatch in the expected base path (api/) that Scrumble might be trying to prepend to your route paths.
2. The error could stem from how Scrumble is configured to recognize and parse your application's routes. It might be expecting a specific format or additional metadata that's not present. Also like compatibility issues between the Scrumble version you're using and your Laravel/Docker setup.
3. Maybe  Missing Annotations that Scrumble requires.

First try Temporarily remove or comment out the GET api/validate and see if your getting another error.

**Comment by CalixteManaud** [comment]
I solved this problem with a sub-middleware in laravel and it went away
