### ISSUE TITLE
first-class callable syntax is not supported

### ISSUE THREAD

**Issue by vovarudomanenko** [dedoc/scramble#355]
## Summary
An endpoint is not documented when first-class callable syntax is used in a route definition

## Examples
using first-class callable syntax
```php
Route::get('csrf-cookie', (new AuthController())->initializeCsrfCookie(...)); // not documented
```
without using first-class callable syntax
```php
Route::get('csrf-cookie', [AuthController::class, 'initializeCsrfCookie']); // documented
```

**Comment by romalytvynenko** [comment]
@vovarudomanenko it is a known limitation. For now both this and closures are not supported
