### ISSUE TITLE
Return type string on extended controller

### ISSUE THREAD

**Issue by terehov-space** [dedoc/scramble#357]
Basic Controller that extends to another controllers, for example usage global pagination responses.

Problem: When in extended Controller we use method from parent class to return response()->json(?) always returning string when using Resource or variable contained Resource data in (?) on parential class

app\Http\Controllers\BasicController.php

```
<?php

namespace App\Http\Controllers;

use App\Http\Resources\ExampleResource;
use App\Services\ExampleService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller as Controller;

class BasicController extends Controller
{
    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function example3(Request $request): JsonResponse
    {
        $responseData = ExampleService::getResponse($request, 'example 3');

        return $this->makeResponse($responseData);
    }

    /**
     * @param mixed $responseData
     * @return JsonResponse
     */
    public function makeResponse(mixed $responseData): JsonResponse
    {
        // this doesn't work
        return response()->json(new ExampleResource($responseData));
        
        // this works
        // return response()->json(['example' => 'response', 'test_data' => 123]);
    }
}
```

Example Controller that extends from BasicController
app\Http\Controllers\ExampleController.php

```
<?php

namespace App\Http\Controllers;

use App\Services\ExampleService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * @method JsonResponse makeResponse(mixed $responseData)
 * @method JsonResponse example3(Request $request)
 * @method JsonResponse example2(Request $request)
 */
class ExampleController extends BasicController
{
    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function example(Request $request): JsonResponse
    {
        $responseData = ExampleService::getResponse($request, 'example');

        return $this->makeResponse($responseData);
    }
}
```

routes/api.php

```
<?php

use Illuminate\Support\Facades\Route;

Route::get('/example', [\App\Http\Controllers\ExampleController::class, 'example'])->name('example');
```

<img width="1800" alt="image" src="https://github.com/dedoc/scramble/assets/71380522/028ad95d-4344-43fe-a1c1-30351c8d9e1d">

**Comment by Jens-dev** [comment]
Same problem here,
we also make heavy use of base Controllers and even a custom base JSONResponse class.
Our Base Controller also holds the validation rules, which also don't get recognized.
We neither get a Request Body nor a Response Body:

<img width="1611" alt="Bildschirmfoto 2024-05-02 um 16 30 59" src="https://github.com/dedoc/scramble/assets/62435371/db418edd-da54-4d1c-94d1-befa6afd7780">

I found this part about extensions in the documentation https://scramble.dedoc.co/developers/extensions
Should we write such an extension to get the logic to recognize our structure?

**Comment by romalytvynenko** [comment]
@Jens-dev can you show some examples of your code base as well?
