### ISSUE TITLE
Selecting API endpoint adds a " " space which cannot be directly pasted

### ISSUE THREAD

**Issue by matthiastjong** [dedoc/scramble#358]
In this example endpoint:

![Screenshot 2024-04-08 at 17 54 10](https://github.com/dedoc/scramble/assets/94455356/aea2888a-9363-48ac-9ba2-f5b1cad5aca3)

If I select the endpoint, and copy it, it will copy it like this: 
```
https://api.example.com/app
/v1/navigation
```

Which in plaintext will be copied as a space. Looking at the HTML it is separated in different html elements:

![Screenshot 2024-04-08 at 17 53 28](https://github.com/dedoc/scramble/assets/94455356/38f6fcaf-636c-4e01-9725-7063bfe69dc1)

Is this intentional? I might be able to cook up a "copy" button on hover that will copy the right string.

**Comment by romalytvynenko** [comment]
@matthiastjong This is the issue of Stoplight UI library, not related to docs generation part hence cannot be fixed as a part of Scramble.
