### ISSUE TITLE
You cannot use arrays in a get request.

### ISSUE THREAD

**Issue by JacobBrassingtonNextLevelSoftware** [dedoc/scramble#360]
I have a GET endpoint which takes filters in the form of an array in an array. For example:

```json
[
    [
        "name",
        "=",
        "john",
    ]
]
```

However as the below shows, you cannot add an array to this parameter.

<img width="927" alt="Screenshot 2024-04-12 at 13 55 13" src="https://github.com/dedoc/scramble/assets/162987050/babe25dd-943a-482a-9f2b-298e2ab919dc">

One possible solution is to allow users to create the parameters for a GET request in a json format similar to postman.

Any thoughts on this would be appreciated.

**Comment by romalytvynenko** [comment]
@JacobBrassingtonNextLevelSoftware I feel like this is the issue of Stoplight UI library, not related to docs generation part hence cannot be fixed as a part of Scramble. Feel free to re-open if you think it's Scramble's issue.

**Comment by emredipi** [comment]
Hi @romalytvynenko, thank you for the package.

Actually this is not related to Stoplight. Package generates wrong response.

Here is my rules
```php
$request->validate([
    'category_ids' => 'array',
    'category_ids.*' => 'numeric',
]);
```


Here is the response of the package which has name as `category_ids`

```json
{
  "name": "category_ids",
  "in": "query",
  "schema": {
    "type": "array",
    "items": {
      "type": "number"
    }
  }
}
```

Here is the correct response which has name as `category_ids[]`

```json
{
    "name": "category_ids[]",
    "in": "query",
    "style": "form",
    "explode": true,
    "schema": {
        "type": "array",
        "items": {
            "type": "number"
        }
    }
}
```

See: https://stackoverflow.com/a/9547490

**Comment by emredipi** [comment]
Hi @romalytvynenko can you open this issue back or should I create a new issue?
