### ISSUE TITLE
Error on v0.10.1

### ISSUE THREAD

**Issue by rcerljenko** [dedoc/scramble#369]
With new update this happens when trying to cache routes:

![image](https://github.com/dedoc/scramble/assets/16762056/f0b430a8-98ad-486c-a18d-7ced13c299a2)

**Comment by xHeaven** [comment]
Same here, this issue appeared in `v0.10.0`.
Something like this also happened in Livewire a while ago. Maybe their PR can help the devs of this package to fix this issue, so I'm just leaving it here: https://github.com/livewire/livewire/pull/6008

**Comment by lloricode** [comment]
same here on my forge deployment 

```
Cannot assign Laravel\SerializableClosure\Serializers\Native to property De  
  doc\Scramble\GeneratorConfig::$routeResolver of type ?Closure 
```

![Screenshot from 2024-05-15 17-23-13](https://github.com/dedoc/scramble/assets/8251344/89ad0766-42f6-4125-8bba-f653c54afb80)

**Comment by romalytvynenko** [comment]
@rcerljenko @lloricode @xHeaven 

Fixing the issue...

**Comment by romalytvynenko** [comment]
@rcerljenko @lloricode @xHeaven

Should be fixed in `0.10.2`!

**Comment by romalytvynenko** [comment]
@rcerljenko @lloricode @xHeaven

You are awesome! Thanks for letting me know!

**Comment by rcerljenko** [comment]
thanks!

**Comment by lloricode** [comment]
> @rcerljenko @lloricode @xHeaven
> 
> You are awesome! Thanks for letting me know!

Thank you for the quick response and fixes 💯

**Comment by rcerljenko** [comment]
unfortunately it still doesn't work for me.. same error  :(

**Comment by xHeaven** [comment]
I'm still experiencing the same @romalytvynenko.

**Comment by lloricode** [comment]
same as mine

```
 Cannot assign Laravel\SerializableClosure\Serializers\Native to property Dedoc\Scramble\GeneratorConfig::$afterOpenApiGenerated of type ?Closure
```

**Comment by romalytvynenko** [comment]
@rcerljenko @lloricode @xHeaven

Gosh... Sorry for that. Fixing

**Comment by rcerljenko** [comment]
no problem  :)

https://www.youtube.com/watch?v=3KDnrGdpNZY

**Comment by romalytvynenko** [comment]
@rcerljenko @lloricode @xHeaven

Can you please check `v0.10.3`?

**Comment by rcerljenko** [comment]
WORKS!  :)))

**Comment by romalytvynenko** [comment]
Closing the issue. Will re-open as many times as needed 🥸

**Comment by lloricode** [comment]
> @rcerljenko @lloricode @xHeaven
> 
> Can you please check `v0.10.3`?

Will be right back as soon, i just have doing grocery 😁

**Comment by lloricode** [comment]
it works! :rocket: 

![Screenshot from 2024-05-15 19-34-11](https://github.com/dedoc/scramble/assets/8251344/8d3e70ba-08d7-4616-a386-b1ffc0b87d78)

my api docs demo https://ecommerce.lloricode.com/docs/api
can I see yours? :D

**Comment by lloricode** [comment]
@romalytvynenko thanks again for the quick fix :100: :rocket:
