### ISSUE TITLE
Bug in latest version v0.10.11

### ISSUE THREAD

**Issue by rcerljenko** [dedoc/scramble#395]
Hi,

With latest version (v0.10.11) something broke (Octane and cached routes). See images bellow.

![image](https://github.com/dedoc/scramble/assets/16762056/a932e38d-caf6-405a-ab8b-4262107f1b8c)
![image](https://github.com/dedoc/scramble/assets/16762056/6a980c59-efd6-471c-9e1b-ad4208009609)

**Comment by rcerljenko** [comment]
No. Only on latest

**Comment by romalytvynenko** [comment]
@rcerljenko ugh, I have a trouble reproducing it. Any chance you can create a repo with this issue?

**Comment by rcerljenko** [comment]
Hi, I can't. It's happening on private project for a company so I can't expose that...  :(

**Comment by romalytvynenko** [comment]
@rcerljenko sure! At the same time you can create a fresh new Laravel project that will have the same issue by figuring out what happens in your private project.

Here are the instructions on how to do that.

1. The first thing to do is to figure out which route is causing the issue. This should be fairly simple. On your error screen go to the "Dumps" section, or check the logs file. You should see which route analysis failed.

2. The next step is isolating this route so only it is added to the documentation. You can do this by adding `@only-docs` annotation to this route method's PHPDoc block.

3. If the analysis still fails, great! You've isolated the route and now you can start figuring out what actually has caused the issue. This is the creative part. Here I recommend you to start commenting out line by line (in your controller, resources, etc) until you see that documentation generation started working. When you find that thing that is breaking everything, you can create a fresh new Laravel app and reproduce this issue there.

Let me know if you have any other questions!

**Comment by rcerljenko** [comment]
Hi. I'll close this since we found a bug on our end regatding route naming...  :)

**Comment by romalytvynenko** [comment]
@rcerljenko gotcha! Still would be useful if you can share the details so I'll be able to handle it in Scramble!
