### ISSUE TITLE
Default config file causes error

### ISSUE THREAD

**Issue by mortenscheel** [dedoc/scramble#44]
Steps to reproduce:

1. Install scramble in clean Jetstream project
2. Publish scramble config
3. Run `php artisan serve`
```
In UrlGenerator.php line 121:

  Illuminate\Routing\UrlGenerator::__construct(): Argument #2 ($request) must be of type Illuminate\Http\Request, null given, called in /Users/**redacted**/vendor/laravel/framew
  ork/src/Illuminate/Routing/RoutingServiceProvider.php on line 67
```
Commenting out the `'api_base_url'` line fixes it

**Comment by romalytvynenko** [comment]
Hey @mortenscheel 

Thank you so much for reporting.

The issue was fixed in `0.5.0`: https://github.com/dedoc/scramble/releases/tag/v0.5.0

P.S.: Please read the release description as the fix is a breaking change and may affect you if you've changed `api_base_url`.
