### ISSUE TITLE
Add a simple way to exclude an endpoint from documentation using annotation

### ISSUE THREAD

**Issue by romalytvynenko** [dedoc/scramble#454]
### Discussed in https://github.com/dedoc/scramble/discussions/234

<div type='discussions-op-text'>

<sup>Originally posted by **rabol** September 25, 2023</sup>
Hi

how to I hide an endpoint so that it does not show up in the documentation?</div>

**Comment by makroxyz** [comment]
It will be nice to have the same annotation to exclude resources too

**Comment by makroxyz** [comment]
I mean... put a docblock like ```@hideFromAPI``` in the resource too

I have some resources used in hidden api routes that I don't want to show...
