### ISSUE TITLE
Defined tags would not replace default tag

### ISSUE THREAD

**Issue by tn710617** [dedoc/scramble#518]
## Context Info
Scramble Version: 0.9.0

## Issue
Occurred maybe from yesterday or today, the defined tags would not replace default tag. For example, a default tag for a controller with name `ExampleController` would be `Example`. 

Before yesterday, after defining a PHPDoc `@tags`, the defined tag did replace the default tag, but now default tag would show no matter if `@tags` is defined as the photo below:

![image](https://github.com/user-attachments/assets/76460fcd-5896-413b-886b-b54d4370e3ec)

**Comment by tn710617** [comment]
> > @tn710617 there were no changes to Scramble 0.9.0. Can you double check the version?
> 
> @romalytvynenko Yes. The version is '0.9.0'. I understand there is no change, and I am also confused. I did git checkout to previous commit and delete the vendor & reinstall, and the result is the same.
> 
> I'm not sure what's going on. It did work properly, and suddenly it broke.

@romalytvynenko 

I would like to add more information
- I use Sail as my local environment, and build my own image in Staging server, and both have this issue. I assume that the environment does not matter for this issue.
- As mentioned, I checked out to previous commit that was made about 1 month ago. Actually I'm sure it was fine a few days ago, but just to be more sure I used the commit made 1 month ago, and the issue was still there. I assume that the issue is not caused by my code.
- I also understand that if the code does not change, it's not quite possible to cause this issue. I checked the API that produced JSON data, and it does show two tags for each path, which I attach a photo below
- According to the aforementioned, maybe the package used some external source to parse directory and generate tags? If so, could you check it?

<img width="530" alt="image" src="https://github.com/user-attachments/assets/028b518c-cbc1-4c21-9412-15998ebd19ae">

**Comment by tn710617** [comment]
> @tn710617 please show your real code examples so we're on the same page

@romalytvynenko 

What code would you need me to provide?

Scramble is simple. I only set up the config and put PHPDoc, and that's it

**Comment by tn710617** [comment]
> @tn710617 the sample of how exactly you use `@tags` annotation

@romalytvynenko 

Sure. I would provide the info below
**route**
```
Route::get('example', [ExampleController::class, 'makeExample'])->name('example');
```

**Controller**
```
/**
 * @tags 範例 - 範例
 */
class ExampleController extends Controller
{

    public function makeExample()
    {
        return response()->json([
            'message' => 'This is an example',
        ]);
    }
}
```

**Result**
<img width="262" alt="image" src="https://github.com/user-attachments/assets/a8a5b4d4-f2c3-4199-9116-fd6ffa56faaa">


Feel free to let me know what info you would need for this issue.

**Comment by tn710617** [comment]
> @tn710617 nice, thanks! Seems like may be related to characters. Will check

@romalytvynenko 

Hi Roma,
For some unaccountable reason, I use `artisan optimize:clear`, and it works again. However, I upgraded the version from '0.9.0' to the latest

I will close this issue, and many thanks for your great work.

**Comment by sotobakar** [comment]
Hello, i seem to be experience this issue as well. I am using the same name for every controller, but i separate it by tag for each Subject (in this case Bendahara Pengeluaran (BPP)). But right now it also shows in the default tag. Can you help?

![image](https://github.com/user-attachments/assets/5143f94b-0c5d-4095-b426-623c4a9286f1)

**Comment by tn710617** [comment]
> artisan optimize:clear

@shokme 

Hey. As mentioned, I did two things to fix it.
- For some unaccountable reason, it seems to be cached. You could try `artisan optimize:clear`. I did fix it by this command.
- I also upgraded to the latest version.
