### ISSUE TITLE
Boolean value becomes a string type when inferring a type

### ISSUE THREAD

**Issue by hagishi** [dedoc/scramble#54]
In `0.5.0`, values of type boolean are converted to type string in the response, is this the expected behavior?

```php
return response()->json(['status' => true]);
```

<img width="237" alt="image" src="https://user-images.githubusercontent.com/473379/194435054-058b7cd0-04b9-4c6e-8f5b-eddb25862283.png">

**Comment by romalytvynenko** [comment]
Hey @hagishi 

It is a bug indeed.

Thanks for reporting, will fix!
