### ISSUE TITLE
Api route resource wrong path for 'show' function

### ISSUE THREAD

**Issue by Jesper-FIltenborg-Dwarf** [dedoc/scramble#61]
When using the Route::resource function in the api.php scramble returns an incorrect route for the show function:

Returns
/api/id/{id}

Expected
/api/user/{id}

**Comment by romalytvynenko** [comment]
@Jesper-FIltenborg-Dwarf can you also show your's controller's method?

Thanks.

**Comment by benpetty** [comment]
I have a similar error using `Route::apiResources` where my routes look like:

```
  GET|HEAD        api/accounts ................. accounts.index › Api\Accounts\AccountsController@index
  POST            api/accounts ................. accounts.store › Api\Accounts\AccountsController@store
  GET|HEAD        api/accounts/{account} ......... accounts.show › Api\Accounts\AccountsController@show
  PUT|PATCH       api/accounts/{account} ..... accounts.update › Api\Accounts\AccountsController@update
  DELETE          api/accounts/{account} ... accounts.destroy › Api\Accounts\AccountsController@destroy
```

But scramble generated paths are:

```
GET     http://localhost/api/accounts
POST    http://localhost/api/accounts
GET     http://localhost/api/ids/{id}
PUT     http://localhost/api/ids/{id}
DELETE  http://localhost/api/ids/{id}
```

As you can see the first two `GET` & `POST` routes are correct but the ones that accept a parameter in the URL are incorrect.

### `routes/api.php`

```php
Route::apiResources([
    'accounts' => AccountsController::class,
    // ...other resources
]);
```


### `app/Http/Controllers/Api/Accounts/AccountsController.php`
```php

class AccountsController extends Controller
{
    public function index()
    {
        // list method...
    }

    public function store(AccountRequest $request)
    {
        // create method...
    }

    public function show($id)
    {
        // view method...
    }

    public function update(AccountRequest $request, $id)
    {
        // update method...
    }

    public function destroy($id)
    {
        // delete method...
    }
}

```

bug is affecting all resources with the same pattern...

**Comment by benpetty** [comment]
It does seem to find the method doc block title/summary but does not generate the request body or response example.

![Screen Shot 2022-10-22 at 12 36 25 PM](https://user-images.githubusercontent.com/22062601/197359275-cd21d8d5-e758-4e9e-a2f9-c0cae546eb84.png)
![Screen Shot 2022-10-22 at 12 38 46 PM](https://user-images.githubusercontent.com/22062601/197359378-a3ee09ae-71a3-42dc-9c3b-0cb432c06c23.png)

**Comment by benpetty** [comment]
I changed the argument name in the controller method from `$id` to `$showFunctionArgumentName` the path changed to this

![Screen Shot 2022-10-23 at 11 26 27 AM](https://user-images.githubusercontent.com/22062601/197409248-50af3283-1b10-4d05-8ad1-0a5660f4512f.png)

**Comment by romalytvynenko** [comment]
Hey @benpetty!

Thank you! This makes sense, I will fix.

🙌
