### ISSUE TITLE
Call to a member function toArray() on null in file

### ISSUE THREAD

**Issue by TiagoAmar0** [dedoc/scramble#62]
The function toArray() in files Dedoc\Scramble\Support\Generator\Combined\AnyOf and Dedoc\Scramble\Support\Generator\Combined\AllOf is not null safe and can throw unexpected errors. Adding null safe operator seems to solve the issue

fn ($item) => $item?->toArray(),

**Comment by romalytvynenko** [comment]
Hey @TiagoAmar0 

Thanks for reporting.

The fix for this issue was pushed in https://github.com/dedoc/scramble/commit/e2bbde02efe1cf1bcc0e73f49b59625a229ef8e4

I will release it in `0.6.0` soon.
