### ISSUE TITLE
Add ability to document request body params (in validation rules): allow overriding a rule, adding description, and example 

### ISSUE THREAD

**Issue by romalytvynenko** [dedoc/scramble#73]
```php
$request->validate([
    /**
     * A foo property.
     *
     * @example 'bar'
     */
    'foo' => 'string',
]);
```

Or simply like so without an example:

```php
$request->validate([
    /** A foo property. */
    'foo' => 'string',
]);
```

Users should be able to override the type as well:
```php
$request->validate([
    /**
     * @var array{bar: string}
     */
    'foo' => 'array',
]);
```

#### Questions

What about comments support? 

Seems like this needs to be supported too, because of responses documenting.

```php
$request->validate([
    // A foo property.
    'foo' => 'string',
]);
```

**Comment by soilSpoon** [comment]
I think it would be nice to use FormRequest's attributes method.

**Comment by romalytvynenko** [comment]
@soilSpoon that would be fun for sure!

Do you have some examples from your real codebase you can share?
