### ISSUE TITLE
Add support for `date` validation rule

### ISSUE THREAD

**Issue by romalytvynenko** [dedoc/scramble#79]

**Comment by romalytvynenko** [comment]
The initially requested feature is solved by adding `@example` support.

**Comment by YournameITManoah** [comment]
@romalytvynenko, the date validation rule is not being translated to a string with date format. What do you mean by `@example` support and how is it supposed to solve this?

**Comment by YournameITManoah** [comment]
> Please create the issue or feel free to submit a PR!

#678
