### ISSUE TITLE
Abort helpers do not add response code to the responses section

### ISSUE THREAD

**Issue by CreepPork** [dedoc/scramble#82]
If using the abort helpers (`abort`, `abort_if`, `abort_unless`), the exception is not added to the responses.

Code example:
```php
public function register(Request $request, Device $device)
{
    $validated = $request->validate(['name' => 'required|string']);

    abort_if($device->registered_at, 400, 'The given device has been already registered.');

    $device->update(array_merge($validated, [
        'registered_at' => now(),
        'last_seen_at' => now(),
    ]));

    return $device->fresh();
}
```

Docs:
![Screenshot_20221130_115449](https://user-images.githubusercontent.com/1590711/204764963-469b3b70-3103-4f22-a075-2d508e265537.png)

**Comment by romalytvynenko** [comment]
@CreepPork 

Will be supported in `0.7.0`! 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/6153876/206911999-ad9f9a27-5814-4350-8e7f-b03a40590a48.png">
