### ISSUE TITLE
Does not work without `doctrine/dbal`

### ISSUE THREAD

**Issue by tontonsb** [dedoc/scramble#98]
The docs imply that scramble will function without `doctrine/dbal`, just the types won't be shown correctly:

> Without the doctrine/dbal, Scramble won't know the types of model attributes, so they will be shown as string in resulting docs.

Instead, the request to `docs/api.json` returns the following message:

> LogicException: `doctrine/dbal` package is not installed. It is needed to get model attribute types. in file /path/to/project/vendor/dedoc/scramble/src/Support/ResponseExtractor/ModelInfo.php on line 73

**Comment by tontonsb** [comment]
Some try-catching might also be useful for cases when `doctrine/dbal` is present, but throws an exception. I ran into this when it failed to recognize the `geometry` type.

It can be solved by adding this block to Laravel's `config/database.php`:

```php
	'dbal' => [
		'types' => [
			'geometry' => '\Doctrine\DBAL\Types\StringType',
		],
	],
```

**Comment by romalytvynenko** [comment]
Hey @tontonsb!

Thanks, this is a bug indeed. Fixing this for the `0.7.0` release which I'm going to release today.

Thanks!
